// src/components/category.js
const categories = [
    "Accounting",
    "AI & Machine Learning",
    "Art & Design",
    "Backend Development",
    "Big Data",
    "Blockchain",
    "Business & Entrepreneurship",
    "Cloud Computing",
    "Content Creation",
    "Cooking",
    "Cyber Security",
    "Data Engineering",
    "Data Science",
    "Digital Marketing",
    "DevOps",
    "Engineering",
    "Event Planning",
    "Frontend Development",
    "Game Development",
    "Grader Courses",
    "Health & Fitness",
    "Interior Design",
    "Kids Courses",
    "Language Learning",
    "Leadership & Management",
    "Law",
    "Literature",
    "Marketing",
    "Mobile Development",
    "Music",
    "Photography",
    "Philosophy",
    "Project Management",
    "Public Speaking",
    "Self-Improvement",
    "Science & Technology",
    "Senior Courses",
    "Software Testing",
    "Sports",
    "Teen Courses",
    "Travel & Tourism",
    "UX/UI Design",
    "Web Development",
    "Web Design",
    "Writing",
  ];
  
  export default categories;
  